{% set name = "radical.analytics" %}
{% set version = "1.102.0" %}
{% set sha256 = "2ed496e380d2eae0aab1e1b3266745e8bd64cd10a1222b0e196b7678c8811a37" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace(".", "_") }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - radical.utils >=1.100,<1.110
    - matplotlib >=3.1.2
    - psutil
    - pandas
    - numpy
    - sqlalchemy
    - more-itertools

test:
  requires:
    - python {{ python_min }}
  imports:
    - radical.analytics

about:
  home: https://github.com/radical-cybertools/radical.analytics
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Analytics is a library supporting the analysis of data produced by RADICAL-Cybertools.
  description: |
    RADICAL-Analytics is a library supporting the analysis of data produced by 
    RADICAL-Cybertools. Currently, RADICAL-Analytics supports RADICAL-Pilot and
    RADICAL-EnTK, and it has been used to support and develop the experimental 
    analysis published by the RADICAL Group at Rutgers University.
  dev_url: https://github.com/radical-cybertools/radical.analytics
  doc_url: https://radicalanalytics.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - mturilli
